var ggdfg={
    "Stts": "SUCCESS",
    "Data": [
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "71.8",
            "rail_shr": "42.58",
            "balnc_shr": "29.22",
            "railble_shr": "5.6",
            "rail_coef_shr": "59.3",
            "non_railble_shr": "23.62",
            "non_railble_res": "1) JSWD IS USING COAL FOR CAPTIVE CONSUMPTION (6 MT) 2) PVT. MGR MOVEMENT OF COAL TO CHANDRAPUR THERMAL POWER HOUSE , MAHGENCO FROM WCL (2.73 MT) 3) SHORT LEAD TRAFFIC IN BB DIVN (1.68 MT) 4) COAL TRAFFIC FROM DIGHI AND KARANJA PORT (1.1 MT) - NO RAIL CONNECTIVITY 5) SHORT LEAD UPTO 200 KMS AND SMALL CUSTOMERS FROM WCL (10.13 MT) 6) LOSS DUE TO LESS YIELD IN WASHING (1 MT)",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "22.51",
            "rail_shr": "9.23",
            "balnc_shr": "13.28",
            "railble_shr": "1.29",
            "rail_coef_shr": "41",
            "non_railble_shr": "11.99",
            "non_railble_res": "SHORT LEAD TRAFFIC WITHIN A 300 KM IS NOT POSSIBLE TO CONVERT INTO RAIL DUE TO ROAD COSTING IS CHEAPER THAN RAIL COST MAINLY DUE TO HIGH HANDLING AT TERMINALS.JSWD CEMENT PRODUCES CEMENT GRANULES FOR WHICH CLASSIFICATION OF PRODUCT IS AWAITED.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "15.01",
            "rail_shr": "6.24",
            "balnc_shr": "8.77",
            "railble_shr": "1.19",
            "rail_coef_shr": "41.6",
            "non_railble_shr": "7.58",
            "non_railble_res": "PRESENTLY NO RAIL SIDING OR GOODS SHED AVAILABLE AT KHOPOLI OR NEAR BY AREAS, HOWEVER, KHOPOLI GOODS SHED (PROPOSED) LOADING WILL ENHANCE.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "19.1",
            "rail_shr": "2.4",
            "balnc_shr": "16.7",
            "railble_shr": ".48",
            "rail_coef_shr": "12.6",
            "non_railble_shr": "16.22",
            "non_railble_res": "TO ACHIEVE ENHANCED LOADING, THERE IS PROVISION OF ADDITIONAL FULL LENGTH GOODS SHED LINE FOR DEALING GOODS SHED TRAFFIC, OTHER THAN THAT DRAINAGE,LABOUR AND MERCHANT ROOM, AND HIGH MAST TO INCREASE NIGHT LOADING HAS BEEN TAKEN UNDER PH- 53 WORKS.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "2.55",
            "rail_shr": ".56",
            "balnc_shr": "1.99",
            "railble_shr": ".17",
            "rail_coef_shr": "22",
            "non_railble_shr": "1.82",
            "non_railble_res": "MAJOR LOADER IS FCI. HANDLING COST IS HIGH & PACKET / CONSIGNMENT SIZE IS SMALL.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "3.68",
            "rail_shr": "3.42",
            "balnc_shr": ".26",
            "railble_shr": ".07",
            "rail_coef_shr": "92.9",
            "non_railble_shr": ".19",
            "non_railble_res": "MAJOR LOADING LOCATION IS KHANDWA AND FERTILIZER COMPANIES ARE LOCATED IN NIMRANI 160 KM AWAY FROM KHANDWA. NEAREST LOADING LOCATION IS SANAWAD OF WCR. WITH INCREASE IN LOADING SUPERPHOSPHATE, QUANTITY/CARGO/PACKET SIZE HAS GONE DOWN.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "27.45",
            "rail_shr": "5.74",
            "balnc_shr": "21.71",
            "railble_shr": "1.47",
            "rail_coef_shr": "20.9",
            "non_railble_shr": "20.24",
            "non_railble_res": "TRAFFIC TRANSPORTED THROUGH PIPELINE 10.1 MT COASTAL SHIPPING 4 MT LOCAL CONSUMPTION IN BOMBAY AREA 3MT  LOCAL PIPELINE TO AIRPORT AND INDUSTRY CONSUMPTION 1.5 MT 2.5 MT BY ROAD",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "57.94",
            "rail_shr": "11.89",
            "balnc_shr": "46.05",
            "railble_shr": "1.2",
            "rail_coef_shr": "20.5",
            "non_railble_shr": "44.85",
            "non_railble_res": "SHORT LEAD UPTO 600 KMS",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "CR",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "30.61",
            "rail_shr": "7.19",
            "balnc_shr": "23.42",
            "railble_shr": "1.82",
            "rail_coef_shr": "23.5",
            "non_railble_shr": "21.6",
            "non_railble_res": "AUTOMOBILE: NON-AVAILABILITY OF RAKES. FLY ASH- 40% CONCESSION REDUCED TO 20% IN MAY- 2023, AGITATION AT UNLOADING POINTS BY LOCAL RESIDENTS, FARMERS. RAW PLANTAIN- HIGHLY PERISHABLE, TRANSIT TIME IS MORE THAN 40 HRS RESULTING IN DAMAGE OF GOODS OTHER COMM.  GOODS LIKE SOYABEAN SEEDS, FODDER/ HUSK, GRAM NOT AVAILABLE IN BULK.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "302",
            "rail_shr": "200.1",
            "balnc_shr": "101.9",
            "railble_shr": "3",
            "rail_coef_shr": "66.3",
            "non_railble_shr": "98.9",
            "non_railble_res": "VIA ROAD MOVEMENT ??? BCCL - 9.5 MT, CCL - 15.2 MT & NCL -16.5 MT.  MGR- 54.0 MT & PIPE - 3.0 MT",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "11.76",
            "rail_shr": "4.97",
            "balnc_shr": "6.79",
            "railble_shr": "1.06",
            "rail_coef_shr": "42.3",
            "non_railble_shr": "5.73",
            "non_railble_res": "SNFC - CEMENT MAINLY DISPATCH BY ROAD TO GIRIDIH, DHANBAD & DEOGHAR AND LOCAL AREA, AS TRANSPORTATION COST BY ROAD IN SHORT LEAD IS LESS AS COMPARED TO RAIL TRANSPORTATION. UCPD - AS PER PRODUCTION MANAGER OF UTCL/UCPD, PRODUCTION OF CEMENT WILL INCREASE 6 TO 7% YEARLY, HENCE LOADING OF CEMENT WILL ENHANCE IN FUTURE.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "1.1",
            "rail_shr": ".36",
            "balnc_shr": ".74",
            "railble_shr": "0",
            "rail_coef_shr": "32.7",
            "non_railble_shr": ".74",
            "non_railble_res": "JSPL - TRANSPORTATION COST  FOR SHORT DISTANCE (LIKE BOKARO, RANCHI, RAMGARH, LOHARDAGA ETC.) IS LESS IN ROAD TRAFFIC IN RESPECT WITH RAIL TRAFFIC.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "9.32",
            "rail_shr": "1.78",
            "balnc_shr": "7.54",
            "railble_shr": "1",
            "rail_coef_shr": "19.1",
            "non_railble_shr": "6.54",
            "non_railble_res": "LOADING OF FOOD GRAIN BY SFCS IS NOT SUSTAINED.  LOCAL MARKET DEMAND IS TRANSPORTED THROUGH ROADWAYS DIRECT FROM VILLAGES. RICE: 75% LOADING THROUGH THE EMPTY FLOW DIRECTION OF ROAD TRAFFIC (COMING FROM NE STATES). WHEAT EXPORT BANNED. SUGAR TRNSPORT AFFECTED DUE TO STATE GOVT POLICY. PADDY ??? CC ISSUE.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "2.42",
            "rail_shr": "2.32",
            "balnc_shr": ".1",
            "railble_shr": ".03",
            "rail_coef_shr": "95.9",
            "non_railble_shr": ".07",
            "non_railble_res": "LOCAL MARKET (WITHIN THE CITY) DEMAND IS TRANSPORTED THROUGH ROADWAYS",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "13.02",
            "rail_shr": "1.4",
            "balnc_shr": "11.62",
            "railble_shr": ".25",
            "rail_coef_shr": "10.8",
            "non_railble_shr": "11.37",
            "non_railble_res": "PIPE-LINE SUPPLY HAS BEEN INTRODUCED, WHICH IS CHEAPER THAN ALL OTHER MODE OF TRANSPORT.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "22.23",
            "rail_shr": "15.57",
            "balnc_shr": "6.66",
            "railble_shr": ".17",
            "rail_coef_shr": "70",
            "non_railble_shr": "6.49",
            "non_railble_res": "INDUSTRIAL SALT LOADING IN CONTAINER SHIFTED TO BOXN. NEPAL BOUND INTERNATIONAL DEMAND IS NOT CONSISTENT.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "EC",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "10",
            "rail_shr": "5.12",
            "balnc_shr": "4.88",
            "railble_shr": ".83",
            "rail_coef_shr": "51.2",
            "non_railble_shr": "4.05",
            "non_railble_res": "FLY ASH: HIGH TRANSPORTATION COST IN RAIL MODE. CONSUMED AT LOCAL CONSTRUCTION SITES IN SEE DIVN.  RED MUD:  CHARGED WITH CLASS-110, WHICH WAS EARLIER CLASS-100.  STONE :  K LICENSE ISSUE WITH STATE GOVT. IN SHK & SPES OF DNR DIVISION. SAND: LOADING IMPACTED DUE TO K LICENSE ISSUE WITH STATE GOVT.  OTHERS ??? PIECEMEAL LOADING IN SEE & SPJ DIV. AFFECTED DUE TO EMPTY FLOW TRANSPORTATION WITH CHEAP FARE.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "218",
            "rail_shr": "160",
            "balnc_shr": "58",
            "railble_shr": "15",
            "rail_coef_shr": "73.4",
            "non_railble_shr": "43",
            "non_railble_res": "10MT BY MGR SYSTEM(NTPC/ KANIHA & NALCO/ BDPK??).NEARLY 25 MT IN SPOT AUCTION BY ROAD MODE. 2MT LOCALLY FROM PPT PORT TO THE INDUSTRIES IN PPT AREA. 6 MT ARE TRANSPORTED BY ROAD TO DIFFERENT COMPANIES AROUND VSKP AREA.",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "13",
            "rail_shr": "11",
            "balnc_shr": "2",
            "railble_shr": "0",
            "rail_coef_shr": "84.6",
            "non_railble_shr": "2",
            "non_railble_res": "2 MT OF LIME STONE BY ROAD TO NEAREST PLANT AREA.",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "7",
            "rail_shr": "1",
            "balnc_shr": "6",
            "railble_shr": "1",
            "rail_coef_shr": "14.3",
            "non_railble_shr": "5",
            "non_railble_res": "THE CEMENT TRANSPORTED TO LOCAL SHORT DISTANCE LESS THAN 200 KM.RAIL TRANSPORTED BY 4 BIG PLANTS LIKE DALMIA/MOIB,JK CEMENT/GHNH, JSW/SKND AND SHREE CEMENT/GHNH IS NEGLIGIBLE.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "40",
            "rail_shr": "21",
            "balnc_shr": "19",
            "railble_shr": "7",
            "rail_coef_shr": "52.5",
            "non_railble_shr": "12",
            "non_railble_res": "I&S IS BEING MOVED BY ROAD TO NEAR BY AREAS, WHICH ARE AROUND 30 TO 40 KM.SLAG IS BEING MOVED BY ROAD TO NEAR BY CEMENT PLANTS LIKE SAGAR CEMENT, SRI SAIRAM CEMENT AND SLAG FROM SMER,MAAL & BPSL TO NEAR BY AREA.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "77",
            "rail_shr": "37",
            "balnc_shr": "40",
            "railble_shr": "32",
            "rail_coef_shr": "48.1",
            "non_railble_shr": "8",
            "non_railble_res": "8 MT BY PIPE LINE FROM NMDC.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "7",
            "rail_shr": "3",
            "balnc_shr": "4",
            "railble_shr": "1",
            "rail_coef_shr": "42.9",
            "non_railble_shr": "3",
            "non_railble_res": "FOOD GRAINS MOSTLY TRANSPORTED BY ROAD FROM SBP AREA TO NEAR BY AREA AND THIS  WILL CONTINUE TO MOVE BY  ROAD.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "8",
            "rail_shr": "6",
            "balnc_shr": "2",
            "railble_shr": "1",
            "rail_coef_shr": "75",
            "non_railble_shr": "1",
            "non_railble_res": "FERTILIZER CARGO IS BEING MOVED BY ROAD TO VSKP,VZM & CHE REGION FOR  DISTRIBUTION.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "5",
            "rail_shr": "4",
            "balnc_shr": "1",
            "railble_shr": "0",
            "rail_coef_shr": "80",
            "non_railble_shr": "1",
            "non_railble_res": "FOR DISTRIBUTION IN URBAN AREAS.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "8",
            "rail_shr": "5",
            "balnc_shr": "3",
            "railble_shr": "1",
            "rail_coef_shr": "62.5",
            "non_railble_shr": "2",
            "non_railble_res": "FOR SMALL POCKET SIZE.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ECO",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "48",
            "rail_shr": "24",
            "balnc_shr": "24",
            "railble_shr": "9",
            "rail_coef_shr": "50",
            "non_railble_shr": "15",
            "non_railble_res": "BAUXITE IS BEING MOVED BY ROAD TO ANRAK ALUMINIUM PLANT LTD. WHICH IS 69 KM FROM VZP/MGPV  ( 1MT TO NEAR BY AREA AND 1 MT TOWRDA TO RAIPUR) MANGANESE ORE MOST OF CARGO IS BEING MOVED BY ROAD TOWARDS RAIPUR AND REST IS NEAR BY SPONGE IRON PLANT LIKE MAHAMAYA, SARADA METALS, BERRY ALLOYS ETC. FLY ASH FROM MAVB,MVAA,MAAL & MGBK BY ROAD TO NEAR BY ARE FOR BRICKS MANUFACTURING PLANTS. OTHER MISC. COMMODITIES THOUGH IT IS RAILABLE LIKE SALT, STONES, SULPHER,CERAMIC PRODUCTS, PAPER PRODUCTS FODDER ,OIL SEEDS, TIN ARTICLES ETC ARE MOVING BY ROAD AS THESE ARE NOT WAGON LOAD QUANTITY.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "76.15",
            "rail_shr": "61.68",
            "balnc_shr": "14.47",
            "railble_shr": "1.95",
            "rail_coef_shr": "81",
            "non_railble_shr": "12.52",
            "non_railble_res": "10 MT IS MOVING IN MGR/NTPC CIRCUIT. 2.52 MT IS BEING TRANSPORTED ON DAILY BASIS IN SMALL VOLUME IN THE DISTANCE RANGE OF 50-100 KM.",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "10.5",
            "rail_shr": "5.94",
            "balnc_shr": "4.56",
            "railble_shr": "1.42",
            "rail_coef_shr": "56.6",
            "non_railble_shr": "3.14",
            "non_railble_res": "THIS TRAFFIC MOVING BY ROAD IN SMALL VOLUME ON DAILY BASIS IN THE DISTANCE RANGE OF 0-200 KM",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "16",
            "rail_shr": "5.24",
            "balnc_shr": "10.76",
            "railble_shr": "2.77",
            "rail_coef_shr": "32.8",
            "non_railble_shr": "7.99",
            "non_railble_res": "TRAFFIC I.E. 4.38 MT CAN NOT BE CAPTURED DUE TO THEIR DEMAND IS IN PIECEMEAL AND COST EFFECTIVENESS. TOTAL PRODUCTION OF SRBS IS 3.61 MT. MILD STEEL PIPES ARE A TYPE OF PRODUCT FROM SRBS WHICH GETS DAMAGED BY MULTIPLE HANDLING AND USED IN REMOTE AREAS AS SEWERAGE PIPES AND IRRIGATION PURPOSE. THEREFORE, THESE CANNOT BE CARRIED BY RAIL. QUANTITY OF ORDER BY CUSTOMERS IS ALSO VERY LOW.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "4.12",
            "rail_shr": ".2",
            "balnc_shr": "3.92",
            "railble_shr": "0",
            "rail_coef_shr": "4.9",
            "non_railble_shr": "3.92",
            "non_railble_res": "APP 1 MT SENT TO PDS, LOCAL CONSUMPTION IS 0.20 MT. REST 2.72 MT IS DISPATCH ON DAILY BASIS IN SMALL VOLUME, THESE CANNOT BE CARRIED BY RAIL DUE TO COST EFFECTIVENESS.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "2.05",
            "rail_shr": "2.01",
            "balnc_shr": ".04",
            "railble_shr": ".04",
            "rail_coef_shr": "98",
            "non_railble_shr": "0",
            "non_railble_res": "PRODUCTS DEMAND IS MAINLY FOR LOCAL CONSUMPTION IN AREAS LIKE BANKURA, BARDHAMAN, HOOGHLY, MURSHIDABAD, MEDINIPORE FOR AGRICULTURAL PURPOSE.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "1.68",
            "rail_shr": ".91",
            "balnc_shr": ".77",
            "railble_shr": ".08",
            "rail_coef_shr": "54.2",
            "non_railble_shr": ".69",
            "non_railble_res": "RESTRICTIONS IN IDBR (ICD BIRGANJ) CAUSES LESS LOADING.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "ER",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "45.61",
            "rail_shr": "20.47",
            "balnc_shr": "25.14",
            "railble_shr": "7.39",
            "rail_coef_shr": "44.9",
            "non_railble_shr": "17.75",
            "non_railble_res": "BOG INCLUDES STONE, BALLAST, FLY ASH, JUTE, RMC ETC. STONE & BALLAST CAN???T BE CAPTURED IN ITS FULL POTENTIAL DUE TO FREQUENT RESTRICTION & CAPACITY CONSTRAINTS OVER ECR. FLY ASH LOADING HAMPERING DUE TO RESTRICTIONS OVER NFR. JUTE IS LOADED BY CONCOR IN CONTAINER & MOVING BY RAIL.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "11.8",
            "rail_shr": "3.65",
            "balnc_shr": "8.15",
            "railble_shr": "1.79",
            "rail_coef_shr": "30.9",
            "non_railble_shr": "6.36",
            "non_railble_res": "NCR HAS ALL CEMENT GRINDING UNITS, HAVING CATCHMENT AREA MAINLY WITHIN 200 KMS. AT PRESENT, DISCOUNT FOR SHORT LEAD TRAFFIC IS UP TO 90 KM. SOME GRINDING UNITS DO NOT HAVE RAIL SIDINGS LIKE ACC & ULTRATECH CEMENT IN DADRI,  JK CEMENT IN BARA & HARDUAGANJ AND MANGALAM CEMENT IN HARDUAGANJ. TEFD PLAYS THE VITAL ROLE. ALL CONSIGNMENTS ARE NOT OF TRAIN LOAD SIZE. DOOR TO DOOR CONSIGNMENT IS CATERED BY ROAD. 3 MAJOR CEMENT SIDINGS HAS 48 % RAIL SHARE",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "3.6",
            "rail_shr": ".91",
            "balnc_shr": "2.69",
            "railble_shr": ".35",
            "rail_coef_shr": "25.3",
            "non_railble_shr": "2.34",
            "non_railble_res": "DUE TO LESS PROCUREMENT BY FCI FOR PDS, FOOD GRAINS LOADING HAS NOT PICKED UP.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "1.7",
            "rail_shr": ".75",
            "balnc_shr": ".95",
            "railble_shr": "0",
            "rail_coef_shr": "44.1",
            "non_railble_shr": ".95",
            "non_railble_res": "THERE IS ONLY ONE FERTILIZER PRODUCTION UNIT I.E. MKFP IN PNKD. MKFP IS LOADING A RAIL COEFFICIENT OF 98%. REASON FOR NON RAILABLE :-IFFCO PHOOLPUR PLANT IN PRAYAGARAJ DISTRICT (CAPACITY-2.6 MTPA)  IS CONNECTED WITH NR.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "12.9",
            "rail_shr": "6.55",
            "balnc_shr": "6.35",
            "railble_shr": ".45",
            "rail_coef_shr": "50.8",
            "non_railble_shr": "5.9",
            "non_railble_res": "DUE TO PROLIFERATION OF PIPELINE, SCOPE OF FURTHER RAIL SHARE IS LESS LIKELY TO INCREASE.LOADING OF ETHANOL AND ATF WILL INCREASE FROM PBCP, KANPUR.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "9.69",
            "rail_shr": "3.33",
            "balnc_shr": "6.36",
            "railble_shr": ".25",
            "rail_coef_shr": "34.4",
            "non_railble_shr": "6.11",
            "non_railble_res": "THERE ARE 04 CONTAINER TERMINALS OVER NCR, I.E. ICDD (DADRI), ICDM MALANPUR), ICDG(KANPUR), ICDY(YAMUNA BRIDGE) OF CONTAINER CORPORATION AND ARIK(KHURJA) &  MKPP(PANKIDHAM) ARE 2 PFTS DEALING WITH CONTAINER",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NC",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "29.02",
            "rail_shr": "5.31",
            "balnc_shr": "23.71",
            "railble_shr": "1.71",
            "rail_coef_shr": "18.3",
            "non_railble_shr": "22",
            "non_railble_res": "STONE & BALLAST -DUE TO WITHDRAWL OF  SAMASTIPUR DIV IN TEFD, BALLAST LOADING OF NCR HAS REDUCED. FLY ASH-DISCOUNT ON FLYASH LOADING HAS BEEN REDUCED FROM 40% TO 20% (WEF 18.05.2023). THIS HAS AFFECTED THE FLYASH LOADING VOLUME. IN F.Y. 2022-23, 286 RAKES WERE LOADED WHEREAS ONLY 200 RAKES COULD BE LOADED IN F.Y.-2023-24. DOC-REASON FOR NON RAILABLE :-  85.13% CONSIGNMENT IS BELOW MINI RAKE SIZE. EDIBLE OIL-REASON FOR NON RAILABLE :-  85.3% IS BEING TRANSPORTED IN SMALL CONSIGNMENT SIZE (BELOW 500T) CAN BE TAPPED ONLY THROUGH AGGREGATORS AND FREIGHT FORWARDERS.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NE",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "7.55",
            "rail_shr": ".5",
            "balnc_shr": "7.05",
            "railble_shr": ".21",
            "rail_coef_shr": "6.6",
            "non_railble_shr": "6.84",
            "non_railble_res": "SHORT LEAD OF TRAFFIC DUE TO HIGHER INTERNAL CONSUMPTION",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NE",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "1.42",
            "rail_shr": "1.21",
            "balnc_shr": ".21",
            "railble_shr": ".1",
            "rail_coef_shr": "85.2",
            "non_railble_shr": ".11",
            "non_railble_res": "DUE TO DEMAND FLUCTUATION IN SPECIFIC SEASONS. SHORT LEAD",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NE",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": ".5",
            "rail_shr": ".39",
            "balnc_shr": ".11",
            "railble_shr": ".11",
            "rail_coef_shr": "78",
            "non_railble_shr": "0",
            "non_railble_res": "",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NE",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "8.35",
            "rail_shr": "2.15",
            "balnc_shr": "6.2",
            "railble_shr": ".33",
            "rail_coef_shr": "25.7",
            "non_railble_shr": "5.87",
            "non_railble_res": "IT MOSTLY INCLUDES SUGAR AND DOC WHICH IS LOCALLY CONSUMED IN NEARBY DISTRICTS.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "6.52",
            "rail_shr": ".42",
            "balnc_shr": "6.1",
            "railble_shr": ".38",
            "rail_coef_shr": "6.4",
            "non_railble_shr": "5.72",
            "non_railble_res": "ISSUES OF RAT HOLE MINING AND BAN ON MEGHALAYA??COAL PENDING JUDICIAL ENQUIRY. MOREOVER, TRUCK MOVEMENT THROUGH BENGAL HAS STARTED WHICH EATS INTO THE RAIL SHARE FOR CHEAPER RATES AS EMPTY TRUCKS PLY TOWARDS NORTHERN INDIA FROM NORTHEASTERN REGION.",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "3.5",
            "rail_shr": "2.18",
            "balnc_shr": "1.32",
            "railble_shr": "1.85",
            "rail_coef_shr": "62.3",
            "non_railble_shr": "-.53",
            "non_railble_res": "POINT TO POINT HANDLING FOR CERTAIN PLANTS IN HOWRAH & ASANSOL DIVISION IS CHEAPER BY ROAD AND DEMAND IS LESS AND SUFFICIENTLY MET BY ROAD TRANSPORTATION.",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "7.11",
            "rail_shr": ".24",
            "balnc_shr": "6.87",
            "railble_shr": ".2",
            "rail_coef_shr": "3.4",
            "non_railble_shr": "6.67",
            "non_railble_res": "SHORT LEAD (<200KMS) AND MULTIPLE HANDLING MAKES ROAD TRANSPORT CHEAPER.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "2.57",
            "rail_shr": ".8",
            "balnc_shr": "1.77",
            "railble_shr": ".88",
            "rail_coef_shr": "31.1",
            "non_railble_shr": ".89",
            "non_railble_res": "LOCAL CONSUMPTION IN STARCH AND ETHANOL FACTORIES IN MUZZAFARPUR, GALGALIA, RAMPUR??AND ADINA. THE LEAD IS SHORT (<150KMS) AND POINT TO POINT HANDLING BY ROAD IS CHEAPER.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "2.62",
            "rail_shr": ".2",
            "balnc_shr": "2.42",
            "railble_shr": ".2",
            "rail_coef_shr": "7.6",
            "non_railble_shr": "2.22",
            "non_railble_res": "ONLY 1 FERTILIZER COMPANY EXISTS IN NFR (BRAHMAPUTRA VALLEY FERTILIZER CORPORATION LTD. LEPETKATA, ASSAM AND RAILWAY CO-EFFICIENT IS MORE THAN 98% 2.62 IS THE TOTAL MARKET SHARE WHICH IS PRIMARILY MET BY INWARD FERTILIZER FOR NFR.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "6.15",
            "rail_shr": "3.4",
            "balnc_shr": "2.75",
            "railble_shr": "3.4",
            "rail_coef_shr": "55.3",
            "non_railble_shr": "-.65",
            "non_railble_res": "LOCAL CONSUMPTION IN NEARBY AREAS OF  TERMINALS/ REFINERIES. PIPELINE CONNECTION TO BIROL/BANGLADESH FROM RANGAPANI (NRSR) ROAD TRANSPORTATION TO BHUTAN, NEPAL AND OTHER NORTHEASTERN STATES (MANIPUR AND MIZORAM) WHERE RAIL CONNECTIVITY IS NOT AVAILABLE.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NF",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "3.42",
            "rail_shr": "3.01",
            "balnc_shr": ".41",
            "railble_shr": "3.42",
            "rail_coef_shr": "88",
            "non_railble_shr": "-3.01",
            "non_railble_res": "",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": ".3",
            "rail_shr": ".15",
            "balnc_shr": ".15",
            "railble_shr": "0",
            "rail_coef_shr": "50",
            "non_railble_shr": ".15",
            "non_railble_res": "LKO-DUE TO CIL POLICY,LESS DEMAND,EXCESS BUFFER STOCK AVAILABLE MANY PLANTS",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "26.65",
            "rail_shr": "3.7",
            "balnc_shr": "22.95",
            "railble_shr": "1.4",
            "rail_coef_shr": "13.9",
            "non_railble_shr": "21.55",
            "non_railble_res": "UMB-THE CEMENT DISPATCHES IN HIMACHAL AREA WHICH IS NOT ACCESSIBLE BY RAILWAYS AND MAJOR PORTION OF DISPATCHES ARE IN SHORT LEAD- NEARBY AREA OF 150 KMS ONLY. DLI- THE TWO CEMENT PLANTS IN DELHI DIVISION ARE IN PANIPAT AND THE CATCHMENT AREA IS 100-150 KM. MAXIMUM MOVEMENT IS BY ROAD. MB-ROAD FERIGHT CHEAPER THAN RAIL FREIGHT, MAINLY SHORT LEAD TRAFFIC TOWARDS UK AREA LKO- ROAD FERIGHT CHEAPER THAN RAIL FREIGHT,SHORT LEAD (20-100KM)",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "34.11",
            "rail_shr": "18.42",
            "balnc_shr": "15.69",
            "railble_shr": "5.2",
            "rail_coef_shr": "54",
            "non_railble_shr": "10.49",
            "non_railble_res": "FZR-3 MT STORED IN GODOWNS, 1.5 MT SENT BY ROAD FOR LOCAL PDS DISTRIBUTION. UMB-MAXIMUM FOOD GRAIN MOVEMENT IS BY FCI AND ROAD FREIGHT IS VERY CHEAP AS COMPARED TO RAIL FREIGHT FOR SHORTER LEAD. DLI- MAXIMUM FOODGRAIN MOVEMENT IS BY FCI. AROUND 2 MT OF PFG RICE IS SHIPPED TO WESTERM PORTS VIA ROAD OR BY CONTAINER. ROAD FREIGHT IS VERY CHEAP AS COMPARED TO RAIL FREIGHT. LKO-STARTING TWO MONTH WHEAT LOADING BAN BY ADMINISTRATION,EXPORT ALREADY BAN",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "9.42",
            "rail_shr": "7.94",
            "balnc_shr": "1.48",
            "railble_shr": "0",
            "rail_coef_shr": "84.3",
            "non_railble_shr": "1.48",
            "non_railble_res": "UMB-SHORT LEAD- NEARBY AREAS OF 150 KMS ONLY. LKO-BY ROAD MOVEMENT AS PER FERTILIZER MIN.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "20.68",
            "rail_shr": "4.99",
            "balnc_shr": "15.69",
            "railble_shr": "0",
            "rail_coef_shr": "24.1",
            "non_railble_shr": "15.69",
            "non_railble_res": "DLI-SLATE IS GIVEN BY RAILWAY BOARD. APART FROM RAIL MAXIMUM POL MOVEMENT IS VIA PIPELINE.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "32.05",
            "rail_shr": "11.81",
            "balnc_shr": "20.24",
            "railble_shr": "1.85",
            "rail_coef_shr": "36.8",
            "non_railble_shr": "18.39",
            "non_railble_res": "",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NR",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "62.99",
            "rail_shr": "7.01",
            "balnc_shr": "55.98",
            "railble_shr": "4.21",
            "rail_coef_shr": "11.1",
            "non_railble_shr": "51.77",
            "non_railble_res": "FZR- ROAD FARE ARE CHEAPER AND HAVE SHORT LEAD. UMB-NMGH/NMGHS & DBKM WAGONS FOR CAPTURING TRACTOR TRAFFIC  IN PEAK SEASON AND UPLIFTING RESTRICTIONS OF 500 KMS ON BOOKING OF TWO-POINT DESTINATION RAKE.POULTRY FEED - DISPATCHES ARE MAINLY TOWARDS SOUTH. RATE OF ROAD AND RAILWAY ARE COMPARABLE FOR SOUTH INDIA (CLASS 100). DOC-CONCERN OF LOADING PARTIES IS THAT AS PER PCC OF BCN WAGONS WEIGHT CHARGED IS FOR 64 TONNES HOWEVER DUE TO BULKY VOLUME OF DOC ONLY 55-58 TONNES IS POSSIBLE TO BE LOADED.IT PROPOSED TO EXPLORE THE CHANGE IN THE CLASS OF COMMODITY FROM EXISTING 120 TO 100. DLI-AUTOMOBILE TRAFFIC IS NOT COMING TO RAIL BECAUSE OF DIFFERENCE IN PRICING OF NMG AND NMGHS WAGONS. JCB TRAFFIC IS DEPENDENT ON AVAILABILITY OF DBKM WAGONS. BRN RATE SHOULD BE EQUALIZED TO THAT OF DBKM RATE. SUGAR EXPORT IS BANNED THUS SUGAR MOVEMENT FROM WESTERN UP IS LOCALIZED. OTHER PIECEMEAL MOVEMENT IS VIA ROAD TOWARDS WESTERN AND SOUTHERN  DUE TO CHEAPER TARIFF. LKO-ROAD FREIGHT IS CHEAPER.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NW",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "40.83",
            "rail_shr": "8.02",
            "balnc_shr": "32.81",
            "railble_shr": "7",
            "rail_coef_shr": "19.6",
            "non_railble_shr": "25.81",
            "non_railble_res": "DUE TO TAKE OVER OF SANGHI-BHUJ BY ADANI GROUP RESULTED INTO DROP OF LOADING FROM ACLR TO GUJARAT AREA AS SANGHI PLANT IS SERVING GUJARAT AREA FROM OCT 23.THESE CEMENT PLANTS ARE NOT HAVING RAIL CONNECTIVITY. ULTRATECH CEMENT PLANT NEAR RAS. (NEW LINE PROPOSED). 2. ULTRATECH CEMENT PLANT NEAR KOTPUTLI. (NEW LINE-SURVEY STAGE) 3. SHREE CEMENT LTD. NAWALGARH.   (PROJECT APPROVED FOR SIDING) 4. SHREE CEMENT LTD. NEAR SURATGARH. (PROJECT APPROVED FOR SIDING) MOSTLY SMALL QUANTITIES ARE TRANSPORTED AT SCATTERED DESTINATIONS & SHORT LEAD TRAFFIC.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NW",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "24",
            "rail_shr": "1.27",
            "balnc_shr": "22.73",
            "railble_shr": "2",
            "rail_coef_shr": "5.3",
            "non_railble_shr": "20.73",
            "non_railble_res": "MOSTLY SMALL QUANTITIES ARE TRANSPORTED AT SCATTERED DESTINATIONS & SHORT LEAD TRAFFIC.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NW",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "1.75",
            "rail_shr": "1.06",
            "balnc_shr": ".69",
            "railble_shr": ".1",
            "rail_coef_shr": "60.6",
            "non_railble_shr": ".59",
            "non_railble_res": "PETROLEUM PRODUCTS ARE TRANSPORTED BY ROAD MAINLY DUE TO TRANSPORTATION OF LESS QUANTITY TO SCATTERED DESTINATIONS",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NW",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "50",
            "rail_shr": "12.41",
            "balnc_shr": "37.59",
            "railble_shr": "11",
            "rail_coef_shr": "24.8",
            "non_railble_shr": "26.59",
            "non_railble_res": "LIGHT WEIGHT CARGO IN LESS QUANTITY FOR DIFFERENT LOCATIONS BY ROAD DOOR TO DOOR DELIVERY.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "NW",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "60.8",
            "rail_shr": "6.34",
            "balnc_shr": "54.46",
            "railble_shr": ".15",
            "rail_coef_shr": "10.4",
            "non_railble_shr": "54.31",
            "non_railble_res": "HEAVY MACHINERY IS TRANSPORTED BY ROAD MAINLY VERY LESS QUANTITY TO A PARTICULAR DESTINATION AND LESS HANDLING IN DOOR TO DOOR TRANSPORTATION. GYPSUM- ONLY 13 RAKES WERE LOADED. THE DECLINE IS BECAUSE OF CHANGE IN POLICY, WHICH LED TO HIGHER TRANSPORTATION COST BY RAIL. LAST YEAR, STS WAS NOT APPROVED AND FURTHER TEFD (TRADITIONAL EMPTY FLOW DIRECTION) BENEFIT WAS WITHDRAWN BY RAILWAYS. THE BALLAST LOADING FROM MAONDA JHILLLO AND NIZAMPUR HAS DECREASED DUE TO COMPLETION OF EDFC WORK. TWO POINT AND THREE-POINT  FERTILIZERS ARE TRANSPORTED BY ROAD MAINLY DUE TO TRANSPORTATION OF LESS QUANTITY TO SCATTERED DESTINATIONS",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "123",
            "rail_shr": "70.52",
            "balnc_shr": "52.48",
            "railble_shr": "4",
            "rail_coef_shr": "57.3",
            "non_railble_shr": "48.48",
            "non_railble_res": "MOVING BY ROAD LESS THAN 100KM DISTANCE OF COAL MINES AND POWER PLANT IS APPROX. 15 KM,  AND THE NEAREST RAIL HEAD IS APPROX. 50 KM COAL IS MOVING BY ROAD",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "60.99",
            "rail_shr": "4.69",
            "balnc_shr": "56.3",
            "railble_shr": "1.5",
            "rail_coef_shr": "7.7",
            "non_railble_shr": "54.8",
            "non_railble_res": "LIMESTONE IS THE MAJOR RAW MATERIAL OF CEMENT MANUFACTURING. CEMENT COMPANIES OWNS THE LIMEMOST OF THE MINES ARE SITUATED BESIDES TO CEMENT PLANTS AND BEING TRANSPORTED BY THEIR OWN AND APPROX. 54.8 MT LIMESTONE IS NON RAILABLE CARGO. APPROX 14.8 MT OF LIMESTONE IS BEING TRANSPORTED BY ROAD BY ULTRATECH CEMENT NEAR JUTURU IN KURNOOL DISTRICT. ULTRATECH CEMENTS TRANSPORTING APPROX. 7 MT OF LIMESTONE FROM THEIR MINES TO CEMENT PLANT IN GADCHANDUR AREA. JSW CEMENT IS TRANSPORTING APPROX. 7.0 MT OF LIMESTONE TO THEIR CEMENT PLANT NEAR PANYAM BY ROAD IN KURNOOL DISTRICT . THE CEMENT FACTORY IS SUPPORTED BY CAPTIVE LIMESTONE MINE LOCATED WITHIN THE VICINITY WITH SUFFICIENT RESERVES.STONE MINES.",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "89.3",
            "rail_shr": "36.27",
            "balnc_shr": "53.03",
            "railble_shr": "3",
            "rail_coef_shr": "40.6",
            "non_railble_shr": "50.03",
            "non_railble_res": "APPROX 11.4 MT OF BULK CEMENT(LOOSE CEMENT) IS MOVING BY ROAD TO DIFFERENT DESTINATION I.E HYDERABAD, BANGALORE, CHENNAI, PUNE, NAGPUR CHANDRAPUR ETC. AVERAGE LEAD IS BETWEEN 300- 400 KM. APPROX 35  MT OF BAGGED CEMENT  IS BEING TRANSPORTED BY ROAD FROM CEMENT PLANTS TO VARIOUS DESTINATION LIKE HYDERABAD, TIRUPATI, NELLORE, BANGALORE, CHENNAI, PUNE, NAGPUR CHANDRAPUR ETC. AVERAGE LEAD IS BETWEEN 300- 400 KM. APPROX 3.5 MT OF BAGGED CEMENT IS BEING TRANSPORTED BY ROAD TO VARIOUS DESTINATION IN VISHAKHAPATNAM, SRIKAKULAM, COIMBATORE, SHIMOGA, HASAN, IRUGUR. AVERAGE LEAD IS APPROX. 400-600 KM",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "4.69",
            "rail_shr": "3.74",
            "balnc_shr": ".95",
            "railble_shr": ".5",
            "rail_coef_shr": "79.7",
            "non_railble_shr": ".45",
            "non_railble_res": "",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "8.9",
            "rail_shr": "7.4",
            "balnc_shr": "1.5",
            "railble_shr": ".1",
            "rail_coef_shr": "83.1",
            "non_railble_shr": "1.4",
            "non_railble_res": "1.4 MT OF FOOD GRAIN IS MOVING  IN VARIOUS DISTRICT OF  AP & TS  BY ROAD FOR LOCAL CONSUMPTION",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "11.9",
            "rail_shr": "7.88",
            "balnc_shr": "4.02",
            "railble_shr": ".1",
            "rail_coef_shr": "66.2",
            "non_railble_shr": "3.92",
            "non_railble_res": "3.92 MT OF FERTILIZER IS MOVING  IN VARIOUS DISTRICT OF  AP & TS  BY ROAD FOR LOCAL CONSUMPTION",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "1.11",
            "rail_shr": "1.1",
            "balnc_shr": ".01",
            "railble_shr": "0",
            "rail_coef_shr": "99.1",
            "non_railble_shr": ".01",
            "non_railble_res": "",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "4.25",
            "rail_shr": "2.39",
            "balnc_shr": "1.86",
            "railble_shr": ".5",
            "rail_coef_shr": "56.2",
            "non_railble_shr": "1.36",
            "non_railble_res": "",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SC",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "34.5",
            "rail_shr": "7.13",
            "balnc_shr": "27.37",
            "railble_shr": "3.29",
            "rail_coef_shr": "20.7",
            "non_railble_shr": "24.08",
            "non_railble_res": "4.3 MT OF FLY ASH IS MOVING BY ROAD FROM VARIOUS POWER PLANT . 1.5 MT OF GRANITE FOR EXPORT TO AKPK & KSLK PORT IS MOVED BY ROAD FROM KARIMNAGAR DISTRICT OF TELANGANA & NELLORE DISTRICT OF AP . APPROX 1.6 MT OF GRANITE IS MOVED BY ROAD FOR INTERNAL CONSUMPTION.4.25 MT OF LATERITE FROM SANGA REDDY DISTRICT OF TELANGANA AND KAKINADA DISTRICT OF ANDHRA PRADESH IS MOVING BY ROAD. FROM SADASHIVAPET ROAD LATERITE IS GOING TO NEAR BY CEMENT PLANTS.3.85 MT OF BARYTE POWDER AND LUMPS FROM KODUR AREA OF ANDHRA PRADESH TO AKPK & CHENNAI PORT IS MOVING BY ROAD. 2.15 MT OF AUTOMOBILE TRAFFIC IN SC DIVISION AND NED DIVISION IS MOVING BY ROAD TO VARIOUS DESTINATIONS. 1.9 MT  OF SUGAR IN NED, HYB & SC DIVISION IS MOVING BY ROAD FOR LOCAL CONSUMPTION ONION-0.95 MT, EDIBLE OIL-0.95 MT, GYPSUM-0.25 MT, PHOSPHORIC ACID-0.66 MT ,BENTONITE-0.29 MT , AMMONIA-0.27 MT , SULPHURIC ACID- 0.25 MT, FELDSPAR-0.25 MT, DE OILED CAKE-0.15 MT, QUARTZ- 0.15 MT, TIMBER WASTE-0.11 MT IS MOVING BY ROAD IN PEACE MEALT.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "73.1",
            "rail_shr": "62.08",
            "balnc_shr": "11.02",
            "railble_shr": "5.9",
            "rail_coef_shr": "84.9",
            "non_railble_shr": "5.12",
            "non_railble_res": "SHORT DISTANCE TRAFFIC IN SMALL QUANTITY",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "4.96",
            "rail_shr": "4.61",
            "balnc_shr": ".35",
            "railble_shr": ".08",
            "rail_coef_shr": "92.9",
            "non_railble_shr": ".27",
            "non_railble_res": "BIG STEEL CUSTOMERS LIKE TATA, JSW TRANSPORT RAW MATERIALS THROUGH MULTIPLE LOGISTIC PROVIDER TO AVOID DEPENDENCY ON SINGLE MODE OF TRANSPORT.",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "27.81",
            "rail_shr": "16.63",
            "balnc_shr": "11.18",
            "railble_shr": "4.05",
            "rail_coef_shr": "59.8",
            "non_railble_shr": "7.13",
            "non_railble_res": "SHORT DISTANCE TRAFFIC ESPECIALLY UPTO 300 KM HAS HIGHER TRANSPORTATION COST INCLUDING HANDING COST THOUGH RAIL FREIGHT IS MUCH CHEAPER THAN ROAD FREIGHT. DAY BY DAY CEMENT INDUSTRY REACHES NEAR THE KEY MARKET AREA INSTALLING MULTIPLE GRINDING UNITS.CUSTOMERS ARE NOT CHOOSING RAILWAY FOR THEIR BULK CEMENT TRANSPORTATION DUE TO NON-AVAILABILITY OF SPECIFIC INFRASTRUCTURE FOR UNLOADING AT DESTINATION",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "37.99",
            "rail_shr": "20.6",
            "balnc_shr": "17.39",
            "railble_shr": "4.41",
            "rail_coef_shr": "54.2",
            "non_railble_shr": "12.98",
            "non_railble_res": "SHORT DISTANCE TRAFFIC IN LESS THAN TRAIN LOAD.GOODS TRAIN AVG. SPEED IS EVEN 25 KMPH RESULTING INTO SUBSTANTIAL TRAVEL TIME TO REACH DESTINATION. HENCE, IT IS NOT PREFERRED MODE OF TRANSPORT SOMETIME.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "170.73",
            "rail_shr": "110.36",
            "balnc_shr": "60.37",
            "railble_shr": "11.82",
            "rail_coef_shr": "64.6",
            "non_railble_shr": "48.55",
            "non_railble_res": "1.NON-AVAILABILITY OF RAKES AND FREQUENT CONGESTION IN ROUTES/DESTINATIONS. 2. DISTANT RAIL-HEAD FROM NEW MINES. 3. PIPE-LINE TRAFFIC, SHORT DISTANCE TRAFFIC AND LESS THAN TRAIN LOAD TRAFFIC.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "1.09",
            "rail_shr": ".12",
            "balnc_shr": ".97",
            "railble_shr": ".05",
            "rail_coef_shr": "11",
            "non_railble_shr": ".92",
            "non_railble_res": "SMALL QUANTITY OF TRAFFIC AT ONE GO. LACK OF WAREHOUSING FACILITY. COVERED STOCKS ARE NOT RELIABLE IN MONSOON SEASON.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "1.01",
            "rail_shr": ".89",
            "balnc_shr": ".12",
            "railble_shr": ".05",
            "rail_coef_shr": "88.1",
            "non_railble_shr": ".07",
            "non_railble_res": "SMALL QUANTITY OF TRAFFIC IN SHORT DISTANCE",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "6.1",
            "rail_shr": "1.8",
            "balnc_shr": "4.3",
            "railble_shr": ".98",
            "rail_coef_shr": "29.5",
            "non_railble_shr": "3.32",
            "non_railble_res": "SMALL QUANTITY OF TRAFFIC IN SHORT DISTANCE. LACK OF HANDLING INFRASTRUCTURE FOR SUCH TRAFFIC.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "3.2",
            "rail_shr": "1.73",
            "balnc_shr": "1.47",
            "railble_shr": "1.18",
            "rail_coef_shr": "54.1",
            "non_railble_shr": ".29",
            "non_railble_res": "NO FIXED TRANSIT TIME IS THERE IN RAILWAYS OWING TO CUSTOMERS NON-PREFERRED MODE OF TRANSPORT.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SE",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "10.32",
            "rail_shr": "6.18",
            "balnc_shr": "4.14",
            "railble_shr": "1.95",
            "rail_coef_shr": "59.9",
            "non_railble_shr": "2.19",
            "non_railble_res": "NON-AVAILABILITY OF BOXN STOCK. CONGESTION IN PATH",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "271.59",
            "rail_shr": "193.7",
            "balnc_shr": "77.89",
            "railble_shr": "41.22",
            "rail_coef_shr": "71.3",
            "non_railble_shr": "36.67",
            "non_railble_res": "SHORT LEAD TRAFFIC SMALL SIZE CARGO",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "42.28",
            "rail_shr": "25.84",
            "balnc_shr": "16.44",
            "railble_shr": "4.37",
            "rail_coef_shr": "61.1",
            "non_railble_shr": "12.07",
            "non_railble_res": "SHORT LEAD TRAFFIC  AND SMALL SIZE CARGO",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "18.84",
            "rail_shr": "8.68",
            "balnc_shr": "10.16",
            "railble_shr": "1.66",
            "rail_coef_shr": "46.1",
            "non_railble_shr": "8.5",
            "non_railble_res": "1. SHORT LEAD TRAFFIC 2. SMALL SIZE CARGO",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "37.01",
            "rail_shr": "12.42",
            "balnc_shr": "24.59",
            "railble_shr": "3.32",
            "rail_coef_shr": "33.6",
            "non_railble_shr": "21.27",
            "non_railble_res": "PRODUCTION OF 5 MT IRON ORE FROM PRIVATE MINES OF SMALL STEEL PLANTS IN CHHATTISGARH - NOT RAILABLE DUE TO LOCAL ISSUES. OUT OF 5 MT PRODUCTION FROM JABALPUR AREA, 2-3 MT IRON ORE  BEING LOADED FROM WCR. OUT OF 10 MT PRODUCTION OF KELZAR AREA, 6-7 MT IRON ORE BEING LOADED FROM SCR & CR. IRON ORE PELLETS (4-5 MILLION TONNES)COULD NOT BE LOADED IN RAIL DUE TO RTP POLICY OF STATE GOVT.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "8",
            "rail_shr": "5.2",
            "balnc_shr": "2.8",
            "railble_shr": "1.36",
            "rail_coef_shr": "65",
            "non_railble_shr": "1.44",
            "non_railble_res": "LOCAL CONSUMPTION",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": ".1",
            "rail_shr": ".02",
            "balnc_shr": ".08",
            "railble_shr": "0",
            "rail_coef_shr": "20",
            "non_railble_shr": ".08",
            "non_railble_res": "SCARCE DEMAND",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "2.65",
            "rail_shr": ".92",
            "balnc_shr": "1.73",
            "railble_shr": "0",
            "rail_coef_shr": "34.7",
            "non_railble_shr": "1.73",
            "non_railble_res": "HINTERLAND CONSUMPTION",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "2.4",
            "rail_shr": "1.31",
            "balnc_shr": "1.09",
            "railble_shr": "0",
            "rail_coef_shr": "54.6",
            "non_railble_shr": "1.09",
            "non_railble_res": "HINTERLAND CONSUMPTION",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SEC",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "89.5",
            "rail_shr": "11.91",
            "balnc_shr": "77.59",
            "railble_shr": "7.53",
            "rail_coef_shr": "13.3",
            "non_railble_shr": "70.06",
            "non_railble_res": "BALANCE PRODUCTION IS OF CAPTIVE LIME STONE MINES OF CEMENT PLANTS OF RAIPUR CLUSTER. LIMITED FLY ASH LOADING & UNLOADING INFRASTRUCTURE",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "93",
            "rail_shr": "23.5",
            "balnc_shr": "69.5",
            "railble_shr": "7.1",
            "rail_coef_shr": "25.3",
            "non_railble_shr": "62.4",
            "non_railble_res": "MOVED BY CONVEYOR(53 MT) AND SHORT LEAD MOVEMENT BY ROAD TO DESTINATIONS NOT HAVING RAIL HEAD/SIDINGS.",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "27.1",
            "rail_shr": "1.7",
            "balnc_shr": "25.4",
            "railble_shr": "1.3",
            "rail_coef_shr": "6.3",
            "non_railble_shr": "24.1",
            "non_railble_res": "SHORT LEAD/ RAIL MOVEMENT COST IS MORE THAN ROAD RATE DUE TO SECONDARY HANDLING AND TRANSPORATION. THE CEMENT COMPANIES HAVE DEVELOPED GRINDING/BAGGING UNITS SO AS TO REDUCE THE DISTRIBUTION LEAD WITHIN 100 KM, WHICH IS NOT FEASIBLE TO MOVE BY RAIL.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "2.4",
            "rail_shr": ".2",
            "balnc_shr": "2.2",
            "railble_shr": ".2",
            "rail_coef_shr": "8.3",
            "non_railble_shr": "2",
            "non_railble_res": "CUSTOMER IS MOVING IT IN LOW VOLUMES TO VARIOUS DESTINATIONS. SHORT LEAD TRAFFIC BY ROAD.LONG LEAD TRAFFIC BY ROAD IN LOW VOLUME.",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "2.6",
            "rail_shr": ".4",
            "balnc_shr": "2.2",
            "railble_shr": "0",
            "rail_coef_shr": "15.4",
            "non_railble_shr": "2.2",
            "non_railble_res": "IRON-ORE FINES MOVING FROM NEW MANGALORE PORT IN LOW VOLUMES TO VARIOUS DESTINATIONS IN BALLARI AREA NOT HAVING RAIL HEAD/SIDINGS.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "2.5",
            "rail_shr": "2",
            "balnc_shr": ".5",
            "railble_shr": "0",
            "rail_coef_shr": "80",
            "non_railble_shr": ".5",
            "non_railble_res": "SHORT LEAD MOVEMENT BY ROAD.SEASONAL TRAFFIC DEPENDING ON MONSOON.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "5.6",
            "rail_shr": "4.3",
            "balnc_shr": "1.3",
            "railble_shr": "0",
            "rail_coef_shr": "76.8",
            "non_railble_shr": "1.3",
            "non_railble_res": "ALREADY RAIL CO-EFFICIENT IS HIGH.  REMAINING QUANTITY IS MOVED TO SHORT LEADS AND IN LOW VOLUMES.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "25.8",
            "rail_shr": "4.9",
            "balnc_shr": "20.9",
            "railble_shr": "0",
            "rail_coef_shr": "19",
            "non_railble_shr": "20.9",
            "non_railble_res": "MOVED BY PIPELINE (17.3 MT) AND BY ROAD (3.6 MT) TO SHORT LEAD",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "38.6",
            "rail_shr": "1.2",
            "balnc_shr": "37.4",
            "railble_shr": "2.2",
            "rail_coef_shr": "3.1",
            "non_railble_shr": "35.2",
            "non_railble_res": "MOVEMENT BY ROAD WITHIN 100 KM RADIUS FROM CHENNAI PORT AND  UP TO 300 KM FROM TUTICORIN AND COCHIN PORTS. DPD/DPE CONTAINERS MOVED DIRECTLY TO/FROM CUSTOMERS BY ROAD.",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SR",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "28.8",
            "rail_shr": "3.2",
            "balnc_shr": "25.6",
            "railble_shr": "4.1",
            "rail_coef_shr": "11.1",
            "non_railble_shr": "21.5",
            "non_railble_res": "TRAIN LOAD CONSIGNMENTS ARE NOT AVAILABLE FOR EDIBLE OIL (2.6 MT) TEXTILES (1.5 MT), SALT (2 MT), & ELECTRICAL AND ELECTRONICS (3.3 MT). HENCE, MOVED BY ROAD IN SMALL VOLUMES TO MUTIPLE DESTINATIONS. HEAVY ENGINEERING AND MACHINERY USED FOR CONSTRUCTION (2.2 MT) COULD NOT BE MOVED DUE TO NON AVAILABILITY OF SPECIAL TYPE OF WAGONS (WELL WAGONS). SUGAR (1 MT) MOVEMENT IS BASED ON FREIGHT DIFFERENTIAL BETWEEN REGIONS FOR LONG DISTANCES AND MOVED BY ROAD TO SHORT LEAD DESTINATIONS. RAW MATERIALS TO FERTILIZER PLANTS (1 MT) MOVED BY ROAD FROM PORT TO PLANT (WITHIN 20 KM) 5) QUARY PRODUCTS (2.5 MT) ARE MOVED IN SMALL VOLUMES TO MULIPLE DESTINATIONS BASED STATE GOVERNMENT PERMIT.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "10.603",
            "rail_shr": "9.974",
            "balnc_shr": ".63",
            "railble_shr": "0",
            "rail_coef_shr": "94.1",
            "non_railble_shr": ".63",
            "non_railble_res": "LOCAL CONSUMPTION AT GOA AREA",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "2.156",
            "rail_shr": "1.102",
            "balnc_shr": "1.05",
            "railble_shr": ".2",
            "rail_coef_shr": "51.1",
            "non_railble_shr": ".85",
            "non_railble_res": "FOR RAIL CONNECTIVITY IN THE LOKAPUR AREA - THIS WILL BECOME RAIL ABLE WITH NEW LINE BETWEEN BGK-KUD",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "9.63",
            "rail_shr": "1.132",
            "balnc_shr": "8.5",
            "railble_shr": ".2",
            "rail_coef_shr": "11.8",
            "non_railble_shr": "8.3",
            "non_railble_res": "1. LOCAL CONSUMPTION 2. FOR RAIL CONNECTIVITY IN THE LOKAPUR AREA - THIS WILL BECOME RAIL ABLE WITH NEW LINE BETWEEN BGK-KUD",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "15.654",
            "rail_shr": "8.788",
            "balnc_shr": "6.87",
            "railble_shr": ".5",
            "rail_coef_shr": "56.1",
            "non_railble_shr": "6.37",
            "non_railble_res": "JSW IS MOVING ABOUT 35% BY ROAD FOR LESS THAN TRAIN LOAD CONSIGNMENTS AND PRODUCTION BY SMALL SCALE STEEL PLANTS",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "37.545",
            "rail_shr": "22.197",
            "balnc_shr": "15.35",
            "railble_shr": "1",
            "rail_coef_shr": "59.1",
            "non_railble_shr": "14.35",
            "non_railble_res": "8.0 MT IS MOVED BY CONVEYOR BELT TO JSWT, BALANCE IS USED BY LOCAL FOUNDRIES AND SMALL-SCALE STEEL PLANTS FOR WHICH THE VOLUME IS LESS THAN TRAIN LOAD.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "16.016",
            "rail_shr": ".083",
            "balnc_shr": "15.93",
            "railble_shr": ".1",
            "rail_coef_shr": ".5",
            "non_railble_shr": "15.83",
            "non_railble_res": "LOCAL CONSUMPTION. RAIL MOVEMENT DEPENDENT ON PRODUCTION AND DEMAND IN OUTSIDE AREAS",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "1.1",
            "rail_shr": ".923",
            "balnc_shr": ".18",
            "railble_shr": "0",
            "rail_coef_shr": "83.9",
            "non_railble_shr": ".18",
            "non_railble_res": "LOCAL CONSUMPTION IN GOA AND NEARBY AREA",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "8",
            "rail_shr": "2.105",
            "balnc_shr": "5.9",
            "railble_shr": "0",
            "rail_coef_shr": "26.3",
            "non_railble_shr": "5.9",
            "non_railble_res": "LOCAL TRAFFIC FROM OIL DEPOTS TO RETAILERS",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "2.4",
            "rail_shr": ".783",
            "balnc_shr": "1.62",
            "railble_shr": ".05",
            "rail_coef_shr": "32.6",
            "non_railble_shr": "1.57",
            "non_railble_res": "ROAD IS PREFERRED BY CUSTOMERS FOR SAVING TIME, MULTIPLE HANDLING AND DOOR-TO-DOOR CONNECTIVITY FOR PORT",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "SW",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "13.07",
            "rail_shr": "3.287",
            "balnc_shr": "9.78",
            "railble_shr": ".4",
            "rail_coef_shr": "25.1",
            "non_railble_shr": "9.38",
            "non_railble_res": "SUGAR -LOCAL AND NEARBY MARKET CONSUMPTION.DEPENDENT ON EXPORT QUOTA.GRANITE-NON-BULK MOVEMENT. PART OF THEE EXPORT TRAFFIC IS COMING TO RAIL WHEN TRAIN LOAD MATERIAL IS BEING SHIPPED. SHORT ??? LEAD TRAFFIC OF AUTOMOBILES. SUPPLY OF NMG IS LIMITED DURING PEAK DEMAND OF FESTIVAL PERIOD.OTHERS-FODDER, COPRA, ARECNUT AND OTHER SMALL SCALE INDUSTRY PRODUCTS ARE VERY SMALL QUANTITY.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "13.5",
            "rail_shr": "10.22",
            "balnc_shr": "3.28",
            "railble_shr": "1.3",
            "rail_coef_shr": "75.7",
            "non_railble_shr": "1.98",
            "non_railble_res": "ADEQUATE SUPPLY OF RAKES IS REQUIRED TO BE ENSURED FOR COAL LOADING. INFRASTRUCTURE IMPROVEMENTS ARE REQUIRED AT GOODS SHEDS LIKE SARAIGRAM & DEORAGRAM. AT PRESENT ENGINEERING BALLAST SIDINGS HAVE BEEN UTILIZED FOR COAL LOADING.??",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "RMSP",
            "cmdt_desc": "RMSP",
            "tot_grft_shr": "2",
            "rail_shr": "1.75",
            "balnc_shr": ".25",
            "railble_shr": "0",
            "rail_coef_shr": "87.5",
            "non_railble_shr": ".25",
            "non_railble_res": "CEMENT PLANTS WITH CLOSE PROXIMITY OF 100-120 KMS BROUGHT LIMESTONE THROUGH ROAD MODE TO AVOID MULTIPLE HANDLING COST.",
            "extra": "2"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "35.41",
            "rail_shr": "21.86",
            "balnc_shr": "13.55",
            "railble_shr": "1.68",
            "rail_coef_shr": "61.7",
            "non_railble_shr": "11.87",
            "non_railble_res": "DUE TO MULTIPLE HANDLING INVOLVED IN TRANSPORTATION OF CEMENT , SHORT LEAD TRAFFIC OF CEMENT WITHIN 125-150 IS TRANSPORTED THROUGH ROAD. SMALL CONSIGNMENTS / PIECEMEAL TRAFFIC?? IS ALSO TRANSPORTED THROUGH ROAD. SOME OF THE DESTINATIONS DO NOT HAVE A FACILITY OF GOODS SHED.",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "IORE",
            "cmdt_desc": "IRON ORE",
            "tot_grft_shr": "5.53",
            "rail_shr": "2.28",
            "balnc_shr": "3.25",
            "railble_shr": "1.66",
            "rail_coef_shr": "41.2",
            "non_railble_shr": "1.59",
            "non_railble_res": "MULTIPLE HANDLING WHICH LEADS TO INCREASE IN TRANSPORT COST AND WASTAGE/WEAR-TEAR OF MATERIAL.",
            "extra": "5"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "21.08",
            "rail_shr": "7.6",
            "balnc_shr": "13.48",
            "railble_shr": "1.61",
            "rail_coef_shr": "36.1",
            "non_railble_shr": "11.87",
            "non_railble_res": "FOOD GRAIN AND OTHER PULSES IS BEING TRANSPORTED BY  ROAD AS SMALL TRAFFIC IN NEAR BY AREAS AS LOCAL CONSUMPTION WHICH ARE PURELY NOT CONNECTED WITH RAILHEADS THUS,  THIS TRAFFIC CANNOT BE DIVERTED TO RAIL.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "5.74",
            "rail_shr": "5.59",
            "balnc_shr": ".15",
            "railble_shr": ".01",
            "rail_coef_shr": "97.4",
            "non_railble_shr": ".14",
            "non_railble_res": "THE PRODUCTION OF FERTILIZER  IS UNDER THE CONTROL OF GOVERNMENT AND MAJOR SHARE OF PRODUCTION IS BEING TRANSPORTED BY RAIL AND VERY MEAGER PART AS SMALL TRAFFIC IS BEING TRANSPORTED IN NEAR BY AREAS AS LOCAL CONSUMPTION.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "3.48",
            "rail_shr": ".85",
            "balnc_shr": "2.63",
            "railble_shr": "0",
            "rail_coef_shr": "24.4",
            "non_railble_shr": "2.63",
            "non_railble_res": "LESS SCOPE DUE TO TRAFFIC SHIFT TO PIPE LINE.",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "1.5",
            "rail_shr": ".97",
            "balnc_shr": ".53",
            "railble_shr": ".66",
            "rail_coef_shr": "64.7",
            "non_railble_shr": "-.13",
            "non_railble_res": "",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WC",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "20.36",
            "rail_shr": "4.964",
            "balnc_shr": "15.4",
            "railble_shr": "2.765",
            "rail_coef_shr": "24.4",
            "non_railble_shr": "12.63",
            "non_railble_res": "BAUXITE & LATERITE -NIWAR GOODS SHED IS HALF RAKE LOADING POINT AND  TERMINAL DETENTION IS AT HIGHER SIDE DUE TO MULTIPLE PLACEMENTS AND REMOVAL. FLY ASH-FOR FULFILLMENT OF REQUIREMENTS IN CEMENT PLANTS OF REWA-SATNA CLUSTER, JPVN AUTHORITIES HAVE MENTIONED THAT ROAD TRAFFIC IS CHEAPER THAN RAILWAY DUE TO SHORT DISTANCE. STONE: EARLIER FOR RAILWAY PROJECTS BALLAST AND STONE HAVE BEEN TRANSPORTED BY M/S GIL SIL JV, PRAYAGRAJ AND M/S K P AWASTHI LIMITED, KATNI. AT PRESENT FOR INFRASTRUCTURE PROJECTS AGGREGATES HAVE BEEN TRANSPORTED THROUGH HYWAS AND TRUCKS.",
            "extra": "10"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "COAL",
            "cmdt_desc": "COAL",
            "tot_grft_shr": "81.59",
            "rail_shr": "12.25",
            "balnc_shr": "69.34",
            "railble_shr": "-1.19",
            "rail_coef_shr": "15",
            "non_railble_shr": "70.53",
            "non_railble_res": "LOCAL CONSUMPTION, <300 KM AND CONVEYOR  AND SCATTERED DEMAND OF BRICKS INDUSTRIES, COMPETITIVE ROAD RATES.",
            "extra": "1"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "CEMT",
            "cmdt_desc": "CEMENT",
            "tot_grft_shr": "66.16",
            "rail_shr": "15.43",
            "balnc_shr": "50.73",
            "railble_shr": "0",
            "rail_coef_shr": "23.3",
            "non_railble_shr": "50.73",
            "non_railble_res": "B2B TRANSACTIONS, LESS THAN 300 KMS AND LOCAL CONSUMPTION, COMPETITIVE ROAD RATES",
            "extra": "3"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "IS",
            "cmdt_desc": "IRON AND STEEL",
            "tot_grft_shr": "21.9",
            "rail_shr": ".98",
            "balnc_shr": "20.92",
            "railble_shr": ".34",
            "rail_coef_shr": "4.5",
            "non_railble_shr": "20.58",
            "non_railble_res": "<300 KM (EXPORT & COASTAL SHIPPING)  AND <16 INCH STEEL PIPE MOVED BY ROAD DUE TO COMPETITIVE ROAD RATE. COST BY RAIL IS ON HIGHER SIDE DUE TO SHORT DISTANCE & SCATTERED DEMAND",
            "extra": "4"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "FG",
            "cmdt_desc": "FOOD GRAINS",
            "tot_grft_shr": "7.63",
            "rail_shr": "1.96",
            "balnc_shr": "5.67",
            "railble_shr": "0",
            "rail_coef_shr": "25.7",
            "non_railble_shr": "5.67",
            "non_railble_res": "LOCAL CONSUMPTION & < 300 KMS.",
            "extra": "6"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "FERT",
            "cmdt_desc": "FERTILIZERS",
            "tot_grft_shr": "20.87",
            "rail_shr": "15.73",
            "balnc_shr": "5.14",
            "railble_shr": "-.05",
            "rail_coef_shr": "75.4",
            "non_railble_shr": "5.19",
            "non_railble_res": "LESS THAN 500 KMS SUBSIDY GIVEN BY FERTILIZER MINISTRY TO ROAD.",
            "extra": "7"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "POL",
            "cmdt_desc": "POL PRODUCTS",
            "tot_grft_shr": "67.2",
            "rail_shr": "12.3",
            "balnc_shr": "54.9",
            "railble_shr": ".84",
            "rail_coef_shr": "18.3",
            "non_railble_shr": "54.06",
            "non_railble_res": "<300 KM, PIPE LINE & MOVING BY SEA AND LACK OF DECANTING FACILITY (ABR ETC.), RETAIL SUPPLY",
            "extra": "8"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "CONT",
            "cmdt_desc": "CONTAINERS",
            "tot_grft_shr": "104.08",
            "rail_shr": "30.79",
            "balnc_shr": "73.29",
            "railble_shr": "3.75",
            "rail_coef_shr": "29.6",
            "non_railble_shr": "69.54",
            "non_railble_res": "LESS THAN <300 KM AND DIRECT PORT DELIVERY, THROUGH CONTAINER FREIGHT STATION & SHIPPING LINE",
            "extra": "9"
        },
        {
            "f_yeaer": "2024-25",
            "zone_name": "WR",
            "cmdy_cd": "BOG",
            "cmdt_desc": "BOG",
            "tot_grft_shr": "144.52",
            "rail_shr": "15.55",
            "balnc_shr": "128.97",
            "railble_shr": ".38",
            "rail_coef_shr": "10.8",
            "non_railble_shr": "128.59",
            "non_railble_res": "EXPORT TRAFFIC TO MUNDRA (> 300 KM) & COMPETITIVE ROAD RATES, DANGEROUS COMMODITY,COASTAL SHIPPING, CONTAINER TRAFFIC, LOCAL CONSUMPTION,VARIOUS TYPE OF GOODS IN SMALL QUANTITY DEAD FREIGHT, MULTIPLE HANDLING, SMALL QUANTITY, HIGHER RAIL FREIGHT ETC.  NEW SPINNING MILLS ARRIVES IN LOCAL VICINITY HENCE ROW COTTON CONSUMED IN NEAR DISTANCE.DUE TO MULTIPLE HANDLINGS, GOODS IS BEING DAMAGED AND FAILED IN QUALITY. LOW DENSITY PRODUCTS RESULTS IN HIGHER TRANSPORTATION VOLUMETRIC TRAFFIC",
            "extra": "10"
        }
    ]
}